export const
    FETCH_WORKOUT_REQUEST = "FETCH_WORKOUT_REQUEST",
    FETCH_WORKOUT_SUCCESS = "FETCH_WORKOUT_SUCCESS",
    FETCH_WORKOUT_FAILURE = "FETCH_WORKOUT_FAILURE";

export const
    POST_WORKOUT_REQUEST = "POST_WORKOUT_REQUEST",
    POST_WORKOUT_SUCCESS = "POST_WORKOUT_SUCCESS",
    POST_WORKOUT_FAILURE = "POST_WORKOUT_FAILURE";